apiVersion: v1
appVersion: "0.2.1"
description: Prometheus metrics exporter for container resources
name: prometheus-container-resource-exporter
version: 0.3.1
home: https://gkarthiks.github.io/container-resource-exporter/
sources:
  - https://github.com/gkarthiks/container-resource-exporter
keywords:
  - prometheus
  - container
  - resource
maintainers:
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
