apiVersion: v1
appVersion: "v1.2.0"
description: Prometheus metrics exporter for Kafka
name: prometheus-kafka-exporter
version: 0.1.1
home: https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
sources:
  - https://github.com/danielqsj/kafka_exporter
keywords:
  - prometheus
  - kafka
maintainers:
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
